server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: salesorder

  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: abc123!
    driverClassName: org.postgresql.Driver

  kafka:
    properties:
      schema.registry.url: http://schema-registry-1:8081

outbox:
  serialization.type: avro

