version: 1
specs:
  topics:
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.orderproc.order-confirmed.event.v11'
    partitions: 8
    replication_factor: 3
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.orderproc.order-cancelled.event.v1'
    partitions: 8
    replication_factor: 3
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.orderproc.order-completed.event.v1'
    partitions: 8
    replication_factor: 3    
