version: 1
specs:
  topics:
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.shop-visited.state.v1'
    partitions: 8
    replication_factor: 3
    configs:
      cleanup.policy: compact
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.shop-user.state.v1'
    partitions: 8
    replication_factor: 3
    configs:
      cleanup.policy: compact
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.sho.search-performed.event.v1'
    partitions: 8
    replication_factor: 3
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.user-logged-in.event.v1'
    partitions: 8
    replication_factor: 3
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.page-navigated.event.v1'
    partitions: 8
    replication_factor: 3    
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.cart-action-occurred.event.v1'
    partitions: 8
    replication_factor: 3        
  - name: '{{ labels.topic.prefix | default('') }}public.ecommerce.shop.product-order-issued.event.v1'
    partitions: 8
    replication_factor: 3        
