
-- USER SQL
CREATE USER customer IDENTIFIED BY "abc123!"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

ALTER USER customer QUOTA UNLIMITED ON "USERS";


-- ROLES
GRANT "CONNECT" TO customer;
GRANT "RESOURCE" TO customer;
ALTER USER customer DEFAULT ROLE "CONNECT","RESOURCE";


    
    