
-- USER SQL
CREATE USER customer IDENTIFIED BY "abc123!"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

ALTER USER customer QUOTA UNLIMITED ON "USERS";


-- ROLES
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO customer;


    
    